### PR TITLE
Update Subclassing.md

### PR DESCRIPTION
**Pull request by kexoth**
You've changed the signature of that method.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by hideya** [comment]
@raymondfeng @bajtos I think this is a small but good fix.  Would you please review it?

**Comment by bajtos** [comment]
@slnode test please

**Comment by bajtos** [comment]
@hideya you are more familiar with the recent changes in the SDK than me or @raymondfeng. If this looks good to you, then please go ahead and land it yourself.

**Pull request merged**
