### PR TITLE
Add support for Date type handling via NSDate

### PR DESCRIPTION
**Pull request by hideya**
This PR allows the developer to declare an NSDate property (instead of current NSString) to deal with the Date type.  Serialized JS Date will get deserialized and set to the NSDate property.

### CODE REVIEW

**Comment by hideya** [comment]
@raymondfeng (cc: @bajtos) would you please review the changes?

**Comment by hideya** [comment]
@rmg would you please help me out?  The automated build seems failing when fetching the changes.  Is there anything I should try on my side?

**Comment by raymondfeng** [comment]
LGTM

**Comment by rmg** [comment]
Sorry for the CI trouble. I _think_ I've cleared it up now. I guess we'll see on the next PR whether it helps any.

**Comment by hideya** [comment]
@rmg thanks for taking care of it!  Appreciated :-)

**Pull request merged**
