### PR TITLE
Fix Issue #51 -- add explicit @synthesize for _id in LBPersistedModel

### LINKED ISSUE #51: LBInstallation _id not set
After updating to the latest version of sdk, my code broke when working with LBInstallation. After digging into it found that it should be related to #40 
I have 2 issues:

1) after `registerDeviceWithAdapter` in success callback, `mode._id` got to null

2) when re-registring (updating an LBInstallation) loopback tries to create existing model here
https://github.com/strongloop/loopback-sdk-ios/blob/master/LoopBack/LBPersistedModel.m#L39
again since `self._id` is null

My code was working with old version of SDK, found no documentation about this... or how to write against the new changes.

### PR DESCRIPTION
**Pull request by hideya**
This fixes Issue #51 (detailed discussions are there).  
@raymondfeng would you please review this one line change? 

Fix #51

### CODE REVIEW

**Comment by raymondfeng** [comment]
LGTM

**Comment by hideya** [comment]
@raymondfeng , is there anything I should do to get this merged?  The error in the checks seem to me caused by some configuration issue...   Please let me know if there is anything I can do.

http://ci.strongloop.com/job/loopback-sdk-ios/93/console
> ERROR: Timeout after 10 minutes
> ERROR: Error fetching remote repo 'origin'

**Comment by hideya** [comment]
@slnode test please

**Comment by bajtos** [comment]
Landed based on approval in https://github.com/strongloop/loopback-sdk-ios/pull/52#issuecomment-128604081. Thank you @hideya for the fix!

**Pull request merged**
