### PR TITLE
Remove docs and docs-1.0

### PR DESCRIPTION
**Pull request by crandmck**
Removing due to use of GPL JS.

### CODE REVIEW

**Comment by crandmck** [comment]
@raymondfeng @chandadharap

**Comment by raymondfeng** [comment]
@crandmck There are a few hand-written markdown files deleted accidentally. Can you revert them?

**Comment by crandmck** [comment]
I added back the .md files.

**Comment by crandmck** [comment]
@raymondfeng Replaced md files and img dirs, and fixed image relative URLs as requested.

**Pull request merged**
